name: langas_user
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  fl_chart: ^0.65.0
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  from_css_color: ^2.0.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^14.8.1
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_path: ^0.7.5
  lottie: ^3.2.0
  page_transition: ^2.2.1
  path: ^1.9.0
  pointer_interceptor: ^0.10.1+2
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  flutter_google_places_hoc081098: ^2.0.0
  google_api_headers: ^4.2.0
  timeago: ^3.2.2
  google_maps_flutter: ^2.10.1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.0
  intl_phone_field: ^3.2.0
  paynow: ^4.2.0
  firebase_core: ^2.30.0 
  firebase_database: ^10.5.0
  firebase_messaging: ^14.7.10 
  flutter_local_notifications: ^17.0.0 
  device_info_plus: ^10.0.0 
  pinput: ^5.0.1
  flutter_svg: ^2.1.0
  card_scanner: ^1.0.2
  ml_card_scanner: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  geolocator_android: 4.6.1

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/pdfs/

  fonts:
    - family: 'Aoboshi One'
      fonts:
        - asset: assets/fonts/AoboshiOne-Regular.ttf