-- liquibase formatted sql

-- changeset jaison.chipuka:1744622352342-1
CREATE TABLE ms_client (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname       VARCHAR(255),
    middle_name     VARCHAR(255),
    lastname        VARCHAR(255),
    mobile_number   VARCHAR(255),
    email_address   VARCHAR(255),
    user_entity_id  BIGINT,
    CONSTRAINT pk_ms_client PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-2
CREATE TABLE ms_deliveries (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price_amount            DECIMAL(30, 4),
    currency                VARCHAR(3),
    sensitivity             VARCHAR(255),
    payment_status          VARCHAR(255),
    pickup_latitude         BIGINT,
    pickup_longitude        BIGINT,
    pickup_location         VARCHAR(255),
    pickup_contact_name     VARCHAR(255),
    pickup_contact_phone    VARCHAR(255),
    drop_off_latitude       BIGINT,
    drop_off_longitude      BIGINT,
    drop_off_location       VARCHAR(255),
    drop_off_contact_name   VARCHAR(255),
    drop_off_contact_phone  VARCHAR(255),
    delivery_instructions   VARCHAR(255),
    parcel_description      VARCHAR(255),
    vehicle_type            VARCHAR(255),
    payment_method          VARCHAR(255),
    delivery_date           TIMESTAMP WITHOUT TIME ZONE,
    package_weight          DECIMAL(30, 4),
    package_height          DECIMAL(30, 4),
    delivery_status         VARCHAR(255),
    reason_for_cancelling   TEXT,
    customer_entity_id      BIGINT,
    driver_entity_id        BIGINT,
    vehicle_entity_id       BIGINT,
    amount                  DECIMAL(30, 4),
    payment_reference       VARCHAR(255),
    CONSTRAINT pk_ms_deliveries PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-3
CREATE TABLE ms_driver (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname           VARCHAR(255),
    lastname            VARCHAR(255),
    email               VARCHAR(255),
    middle_name         VARCHAR(255),
    mobile_number       VARCHAR(255),
    gender              VARCHAR(255),
    address             VARCHAR(255),
    national_id_no      VARCHAR(255),
    driver_license_no   VARCHAR(255),
    approval_status     VARCHAR(255),
    approved_by         VARCHAR(255),
    date_approved       TIMESTAMP WITHOUT TIME ZONE,
    profile_photo_url   VARCHAR(255),
    national_id_image   VARCHAR(255),
    drivers_license_url VARCHAR(255),
    user_entity_id      BIGINT,
    CONSTRAINT pk_ms_driver PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-4
CREATE TABLE ms_users (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname               VARCHAR(255),
    middle_name             VARCHAR(255),
    lastname                VARCHAR(255),
    mobile_number           VARCHAR(255),
    email_address           VARCHAR(255),
    user_password           VARCHAR(255),
    date_joined             TIMESTAMP WITHOUT TIME ZONE,
    user_type               VARCHAR(255),
    enabled                 BOOLEAN NOT NULL,
    account_non_expired     BOOLEAN NOT NULL,
    credentials_non_expired BOOLEAN NOT NULL,
    account_non_locked      BOOLEAN NOT NULL,
    CONSTRAINT pk_ms_users PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-5
CREATE TABLE ms_vehicle (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_model       VARCHAR(255),
    vehicle_color       VARCHAR(255),
    vehicle_make        VARCHAR(255),
    license_plate_no    VARCHAR(255),
    vehicle_type_id     BIGINT,
    vehicle_status_id   BIGINT,
    driver_entity_id    BIGINT,
    active              BOOLEAN,
    CONSTRAINT pk_ms_vehicle PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-6
CREATE TABLE ms_wallet (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    balance             DECIMAL(30, 2),
    credit              DECIMAL(30, 2),
    debit               DECIMAL(30, 2),
    currency_entity_id  BIGINT,
    user_entity_id      BIGINT,
    CONSTRAINT pk_ms_wallet PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-7
CREATE TABLE password_reset_tokens (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token           VARCHAR(255),
    user_entity_id  BIGINT,
    expiry_date     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_password_reset_tokens PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-8
CREATE TABLE sp_available_driver (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_accepted   TIMESTAMP WITHOUT TIME ZONE,
    status          VARCHAR(255),
    longitude       BIGINT,
    latitude        BIGINT,
    driver_id       BIGINT,
    delivery_id     BIGINT,
    CONSTRAINT pk_sp_available_driver PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-9
CREATE TABLE sp_client_rating (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment     TEXT,
    rating      DECIMAL(10, 2),
    delivery_id BIGINT,
    CONSTRAINT pk_sp_client_rating PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-10
CREATE TABLE sp_driver_rating (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment     TEXT,
    rating      DECIMAL(10, 2),
    delivery_id BIGINT,
    CONSTRAINT pk_sp_driver_rating PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-11
CREATE TABLE sp_transaction (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount          DECIMAL(30, 2),
    reference       VARCHAR(255),
    type            VARCHAR(255),
    transaction_id  BIGINT,
    CONSTRAINT pk_sp_transaction PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-12
CREATE TABLE st_currency (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency        VARCHAR(255),
    currency_name   VARCHAR(255),
    active          BOOLEAN,
    CONSTRAINT pk_st_currency PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-13
CREATE TABLE st_user_type (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_name VARCHAR(255),
    CONSTRAINT pk_st_user_type PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-14
CREATE TABLE st_vehicle_status (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_name VARCHAR(255),
    CONSTRAINT pk_st_vehicle_status PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-15
CREATE TABLE st_vehicle_type (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    active  BOOLEAN,
    CONSTRAINT pk_st_vehicle_type PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-16
CREATE TABLE sp_drop_offs (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    drop_off_image  VARCHAR(255),
    otp             VARCHAR(6),
    latitude        BIGINT,
    longitude       BIGINT,
    status          VARCHAR(255),
    timestamp       TIMESTAMP WITHOUT TIME ZONE,
    delivery_id     BIGINT,
    CONSTRAINT pk_sp_drop_offs PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-17
CREATE TABLE sp_pickups (
    entity_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    latitude        BIGINT,
    longitude       BIGINT,
    timestamp       TIMESTAMP WITHOUT TIME ZONE,
    pickup_image    VARCHAR(255),
    delivery_id     BIGINT,
    CONSTRAINT pk_sp_pickups PRIMARY KEY (entity_id)
);

-- changeset jaison.chipuka:1744622352342-18
CREATE TABLE sp_cancel
(
    entity_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp         TIMESTAMP WITHOUT TIME ZONE,
    latitude          BIGINT,
    longitude         BIGINT,
    reason_cancelling VARCHAR(255),
    CONSTRAINT pk_sp_cancel PRIMARY KEY (entity_id)
);

-- changeset dylan.dzvene:1745589005652-4
CREATE TABLE transaction
(
    id                    VARCHAR(255) NOT NULL,
    type                  VARCHAR(255),
    status                VARCHAR(255),
    currency_id           BIGINT,
    principal_amount      DECIMAL(30, 2),
    delivery_id           BIGINT,
    payment_method        VARCHAR(255),
    commission_amount     DECIMAL(30, 2),
    source_wallet_id      BIGINT,
    destination_wallet_id BIGINT,
    commission_wallet_id  BIGINT,
    reference             VARCHAR(255),
    narration             VARCHAR(255),
    client_id             BIGINT       NOT NULL,
    driver_id             BIGINT,
    organization_id       BIGINT,
    date_created          TIMESTAMP WITHOUT TIME ZONE,
    last_updated          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);

-- changeset dylan.dzvene:1745589005652-5
CREATE TABLE wallet_account
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_number  VARCHAR(255),
    owner_type      VARCHAR(255),
    owner_id        BIGINT,
    status          VARCHAR(255),
    type            VARCHAR(255),
    organization_id BIGINT,
    date_created    TIMESTAMP WITHOUT TIME ZONE,
    last_updated    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_walletaccount PRIMARY KEY (id)
);

-- changeset dylan.dzvene:1745589005652-6
CREATE TABLE wallet_balance
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_id          BIGINT                                  NOT NULL,
    amount             DECIMAL(30, 2),
    running_balance    DECIMAL(30, 2),
    transaction_ref    VARCHAR(100),
    balance_type       VARCHAR(255),
    currency_id        BIGINT,
    sub_transaction_id BIGINT,
    date_created       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_walletbalance PRIMARY KEY (id)
);

-- changeset DylanDzvene:1745758581108-7
CREATE TABLE sub_transaction
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id    VARCHAR(255),
    wallet_account_id BIGINT,
    reference         VARCHAR(100),
    payment_method    VARCHAR(255),
    currency_id       BIGINT,
    type              VARCHAR(255),
    amount            DECIMAL(30, 2),
    date_created      TIMESTAMP WITHOUT TIME ZONE,
    date_update       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_subtransaction PRIMARY KEY (id)
);

-- changeset DylanDzvene:1745759426527-1
CREATE TABLE ms_currencies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    alpha_code   VARCHAR(255),
    numeric_code VARCHAR(255),
    status       VARCHAR(255),
    date_created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);